### ISSUE TITLE
Classpath ignored when running jar

### ISSUE THREAD

**Issue by h1tsmart** [Gubaer/josm-scripting-plugin-graaljs#1]
Run JOSM:
java -jar JOSM.jar

man java:
> When you use -jar, the specified JAR file is the source of all user classes, and other class path settings are ignored.

Classpath ignored when running jar

Run JOSM with:
> --module-path /lib --add-modules org.graalvm.sdk,org.graalvm.js,com.oracle.truffle.regex,org.graalvm.truffle

**Comment by pl71** [comment]
How to run under Windows?
Simply downloading GraalJS jar files and adding them to CLASSPATH is not working.

EDIT: Finally it worked as per the above:
`java -jar --module-path "C:\...\graaljs-22.1.0\lib" --add-modules org.graalvm.sdk,org.graalvm.js,com.oracle.truffle.regex,org.graalvm.truffle "C:\Users\User\Desktop\josm-tested.jar"`

openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

Microsoft Windows [Version 10.0.19044.1826]

**Comment by zdila** [comment]
@pl71 thanks! This helped also on Linux where CLASSPATH also didn't work.
